// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'find yours',
    appId: '1:611907047207:web:4b10da26dc23034018e302',
    messagingSenderId: '611907047207',
    projectId: 'soko-fresh-7bd01',
    authDomain: 'soko-fresh-7bd01.firebaseapp.com',
    storageBucket: 'soko-fresh-7bd01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'find yours',
    appId: '1:611907047207:android:8b7dfb8d617d007c18e302',
    messagingSenderId: '611907047207',
    projectId: 'soko-fresh-7bd01',
    storageBucket: 'soko-fresh-7bd01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'find yours',
    appId: 'find yours',
    messagingSenderId: '611907047207',
    projectId: 'soko-fresh-7bd01',
    storageBucket: 'soko-fresh-7bd01.appspot.com',
    iosBundleId: 'com.example.sokoFresh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'find yours',
    appId: find yours',
    messagingSenderId: '611907047207',
    projectId: 'soko-fresh-7bd01',
    authDomain: 'soko-fresh-7bd01.firebaseapp.com',
    storageBucket: 'soko-fresh-7bd01.appspot.com',
  );
}
